config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    collection do
      get :mypost
      resources :likes
    end
  end
  root 'posts#index'
  get 'posts/mypost'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.already_liked?(post_id, user_id)
    Like.where(user_id: user_id, post_id: post_id).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
    has_many:likes, dependent: :destroy
    has_many:users, :through => :likes

    validates :post, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
has_many:likes, dependent: :destroy
has_many:posts, :through => :likes

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => {email: true, login: false}
         validates_uniqueness_of :username
         validates :username, presence: true
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    def create
        if Like.already_liked?(params[:post_id], current_user.id)
          flash[:notice] = "You can't like more than once"
        else
          @post.likes.create(user_id: current_user.id)
        end
        redirect_to posts_path
      end
    
    private
    def find_post
        @post = Post.find(params[:post_id])
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.created_by=current_user.id.to_s
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render posts_url, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.created_by==current_user.id.to_s
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
    else
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Only User who created the post can delete this." }
        format.json { head :no_content }
    end
  end
  end

  def mypost
    @posts = Post.all
  end
  
 

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
    if(@post.created_by!=current_user.id.to_s)
      respond_to do |format|
      format.html { redirect_to posts_url, notice: "What are you doing here?." }
    end
  end
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:post, :created_by, :description,:likes,:liked_by,:dislike,:disliked_by)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to'Website',root_path,class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav navbar-right">
  
      <%if user_signed_in?%>
      <li class="nav-item ">
        <%= link_to'Logout',destroy_user_session_path, method: 'delete' ,class:'nav-link ml-auto'%>
      </li>
      <li class="nav-item ">
        <%= link_to'My Posts',posts_mypost_path,class:'nav-link ml-auto'%>
      </li>
      <%else%>
      <li class="nav-item">
        <%= link_to'Login',new_user_session_path,class:'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to'Sign Up',new_user_registration_path,class:'nav-link'%>
      </li>
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render'home/header'%>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_field :post %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<%if user_signed_in?%>
<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th class="col">Title</th>
      <th class="col">Description</th>
      <th class="col">Likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><b><%= post.post %></b></td>
        <td><%= post.description %></td>
        <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
        <td><%= link_to 'Like', likes_path(post_id: post.id), method: :post %></td>
        <% if post.created_by==current_user.id.to_s%>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path,{:style=>'color:white;', :class => "btn btn-primary"} %>
<%else%>
  <h1>Welcome to our site please Login to continue</h1>
  <%= link_to 'Login', new_user_session_path,{:style=>'color:white;', :class => "btn btn-primary"} %>
<%end%>

app/views/posts/mypost.html.erb
<p id="notice"><%= notice %></p>
<%if user_signed_in?%>
<h1>My Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th class="col">Title</th>
      <th class="col">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
     <% if post.created_by==current_user.id.to_s %>
      <tr>
        <td><%= post.post %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Post', new_post_path,{:style=>'color:white;', :class => "btn btn-primary"} %>
<%else%>
  <h1>Welcome to our site please Login to continue</h1>
  <%= link_to 'Login', new_user_session_path,{:style=>'color:white;', :class => "btn btn-primary"} %>
<%end%>

<%= link_to 'Back To All posts', posts_path,{:style=>'color:white;', :class => "btn btn-primary"} %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.post %>
</p>
<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @post.created_by %>
</p>

<p>
  <strong>Likes:</strong>
  <td><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
</p>


<%= link_to 'Back', posts_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>